spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_bot_db
    username: postgres
    password: 0
    driver-class-name: org.postgresql.Driver

bot:
  name: ${Bot_Name}
  token: ${Bot_Token}
