spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_bot_db
    username: postgres
    password: 0
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

bot:
  name: ${Bot_Name}
  token: ${Bot_Token}
